### ISSUE TITLE
Connection to runner with Pid xxx lost. The runner probably quit unexpectedly. Inspect logs for potential reasons.

### ISSUE THREAD

**Issue by iskoc9002** [getgauge/gauge#1380]
Hi,
I've a problem on IntelliJ 2018.3. get this error in %80 on Debug mode. %50 run mode also. When I use terminal with mvn command, I didn't get an error.

Listening for transport dt_socket at address: 51989

Error ----------------------------------

Connection to runner with Pid 16248 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:51994->127.0.0.1:51998: use of closed network connection

Get Support ----------------------------
Docs: https://docs.gauge.org
Bugs: https://github.com/getgauge/gauge/issues
Chat: https://gitter.im/getgauge/chat

Your Environment Information -----------
windows, 1.0.4, 3a9a647
html-report (4.0.6), java (0.7.2), screenshot (0.0.1)

**Comment by nehashri** [comment]
@iskoc9002 Is it possible to share `gauge.log` file when you face this error. It may help us in identifying when this error occurs.

**Comment by iskoc9002** [comment]
Hi @nehashri , 
I have solved the problem by updating the following parameters in the **gauge.properties** file.

runner_connection_timeout = **15000**
runner_request_timeout = **15000**

Thanks alot.

**Comment by nehashri** [comment]
@iskoc9002 Thanks for letting us know.

**Comment by rohitlamsonge66** [comment]
Facing the same issue but not having any solution.


Connection to runner with Pid 22336 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:64534->127.0.0.1:64541: use of closed network connection

**Comment by iskoc9002** [comment]
> Facing the same issue but not having any solution.
> 
> Connection to runner with Pid 22336 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:64534->127.0.0.1:64541: use of closed network connection

Hi,
Have you tried to change runner_connection_timeout parameters.

**Comment by sanjeeth-07** [comment]
same here! 

`Error ----------------------------------

[Gauge]
Connection to runner with Pid 21244 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:62536->127.0.0.1:62538: use of closed network connection
` 
Any fix for the same??

**Comment by vasanthdama** [comment]
I am also facing the same issue, the worry part here is we are unable to get the html-report for already executed scripts also.. it's completely terminating the job..

[runner: 2] Error: Waiting Failed: Element '[object Object]' not found within 600000 ms
    at waitFor (/var/lib/jenkins/workspace/********/node_modules/taiko/lib/taiko.js:3110:13)
Error ----------------------------------

Connection to runner with Pid 3151 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:46775->127.0.0.1:47820: use of closed network connection

gauage.log:
08:34:48.214 Connection to runner with Pid 3151 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:46775->127.0.0.1:47820: use of closed network connection

**Comment by SergeyShidlovskyi** [comment]
Issue is still actual

**Comment by jannishuebl** [comment]
Any news on this? It's quite annoying. Is there some workaround?

**Comment by SergeyShidlovskyi** [comment]
I resolved this issue just by raising JDK version to 11

**Comment by sanjeeth-07** [comment]
resolved this by updating taiko/gauge to the latest versions.

**Comment by Dr-Wyatt** [comment]
I am still having issues with this as well in C# with VS 2017

**Comment by CosminSontu** [comment]
[Gauge]
Connection to runner with Pid 41944 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:52717->127.0.0.1:52733: use of closed network connection

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	windows, 1.0.6, 2bc49db
	dotnet (0.1.2), html-report (4.0.8), screenshot (0.0.1)
Error: Tests failed.

**Comment by zabil** [comment]
This is most probably not an issue with Gauge but with the environment or the tests. The best bet is to look at logs, console output etc and provide as much information you can about the run.

That said, Gauge is not doing a good job of reporting the right error either. A fix to report the right error will be made soon and hopefully it will much easier to figure out the problem.

**Comment by rohitlamsonge66** [comment]
> > Facing the same issue but not having any solution.
> > Connection to runner with Pid 22336 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:64534->127.0.0.1:64541: use of closed network connection
> 
> Hi,
> Have you tried to change runner_connection_timeout parameters.

yes tried. but above solution does not worked.

**Comment by dalemane** [comment]
This is a serious stopper. We need higher priority to this issue.

**Comment by rohitlamsonge66** [comment]
i have tries with update java version and by updating taiko/gauge to latest version. But still it didn't work for me.

**Comment by CosminSontu** [comment]
Hi,

Getting back with the logs (these lines are produced at every run):

06-02-2020 19:27:06.237 [Gauge] [DEBUG] Plugin dotnet is already installed.
06-02-2020 19:27:06.238 [Gauge] [DEBUG] Plugin html-report is already installed.
06-02-2020 19:27:07.148 [Gauge] [DEBUG] Checking updates...
06-02-2020 19:27:07.149 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/dotnet?l=dotnet&p=dotnet,html-report,screenshot&o=windows&a=amd64
06-02-2020 19:27:08.217 [dotnet] [DEBUG] Loading assembly from : c:\Users\csontu\source\repos\gauge-t\gauge_bin\FluentAssertions.Core.dll
06-02-2020 19:27:08.219 [dotnet] [DEBUG] Loading assembly from : c:\Users\csontu\source\repos\gauge-t\gauge_bin\FluentAssertions.dll
06-02-2020 19:27:08.219 [dotnet] [DEBUG] Loading assembly from : c:\Users\csontu\source\repos\gauge-t\gauge_bin\Gauge.CSharp.Lib.dll
06-02-2020 19:27:08.221 [Gauge] [ERROR] Failed to initialize suite datastore. Error: Connection closed [127.0.0.1:64998] cause: EOF
06-02-2020 19:27:08.232 [Gauge] [INFO] Closing connection [127.0.0.1:65000] cause: EOF
06-02-2020 19:27:08.324 [Gauge] [DEBUG] Plugin [Html Report] with pid [41784] has exited
06-02-2020 19:27:08.324 [Gauge] [INFO] Specifications:	0 executed	0 passed	0 failed	0 skipped
06-02-2020 19:27:08.324 [Gauge] [INFO] Scenarios:	0 executed	0 passed	0 failed	0 skipped
06-02-2020 19:27:08.324 [Gauge] [INFO] 
Total time taken: 405ms

**Comment by sriv** [comment]
Hi, please can you share some more information for us to be able to troubleshoot?

It would be great if you could post the steps that followed that caused this error, along with the environment details(which OS, which language/framework version) and what version of gauge and plugins were used.

If you could share a sample project, that'd be terrific.

Note that the more the details we get, the lesser the time we spend to analzye the issue, and the faster we can ship a fix.

**Comment by sriv** [comment]
Meanwhile, we are going to try and make the error reported more specific.

**Comment by rohitlamsonge66** [comment]
OS - Mac 10.14.6 
Language - Java (tried on version 8,11,13)
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)



Console Logs

Runner Ready for Debugging
Listening for transport dt_socket at address: 59123
log4j:WARN No appenders could be found for logger (org.reflections.Reflections).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/rohitlamsonge/.m2/repository/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Error ----------------------------------

[Gauge]
Connection to runner with Pid 25654 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:59128->127.0.0.1:59132: use of closed network connection

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 1.0.6
	html-report (4.0.8), java (0.7.3), screenshot (0.0.1)

Process finished with exit code 1

**Comment by sriv** [comment]
@rohitlamsonge66 thanks. Can you please try running with `-l debug` ex: `gauge run specs -l debug` ? This should print more information.

**Comment by sriv** [comment]
Sidenote: Gauge `1.0.7` has been released, along with `gauge-java` `0.7.4`. It contains some fixes/improvements. Could you please try upgrading?

**Comment by rohitlamsonge66** [comment]
Tried with updating the 1.0.7 has been released, along with gauge-java 0.7.4. But still facing the same issue.

Listening for transport dt_socket at address: 62591
Error ----------------------------------

[Gauge]
Failed to start gauge API: Timed out connecting to java

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	darwin, 1.0.7
	html-report (4.0.8), java (0.7.4), screenshot (0.0.1)

Process finished with exit code 1

**Comment by rohitlamsonge66** [comment]
This issue only reproduce while debugging. For normal run its work fine.

**Comment by sriv** [comment]
@rohitlamsonge66 - which IDE are you using? I have been debugging with VSCode + gauge plugin and things seem to work.

Also, are you seeing this in any particular project (ex. your test suite) or is this an error even in a newly created Gauge project?

If you are using maven, please ensure that `pom.xml` has gauge-java `0.7.4` in it's dependency

**Comment by sriv** [comment]
Generally speaking, both `Timed out connecting to java` and `Connection to runner with Pid XXX lost.` errors are symptoms that the gauge-java (or other runner that you'd be using) have crashed (or killed unexpectedly).

`Timed out connecting to java` - this is a sign that the runner did not start correctly, and possible causes include:
- unavailability of proper runtime
- incorrect `PATH` setting
- permission issues
(the list is pretty generic)

And when you see `Connection to runner with Pid XXX lost.`, it is a sign that the runner was alive when it was brought up, and over the course of the run, it crashed unexpectedy. The definition of an unexpected crash is that Gauge did not kill it gracefully, at the end of the execution lifecycle.

IIn a low spec machine (ex a container in your build environment)  the cause could be something like the memory usage increased leading to the process being killed.

In either of the above cases, the error message is more a symptom than a cause, and that's what we aim to improve. Feedback/help is most welcome!

### Tracking such failures (Java)

One way to capture the cause of failure would be to enable ErrorFile logging by specifying the `--XXErrorfile:<file_path>` (ref: https://docs.oracle.com/javase/10/troubleshoot/fatal-error-log.htm#JSTGD542). This can be set as `gauge_jvm_args` either in a `properties` file, or as an environment variable.

**Comment by sriv** [comment]
Following up further on this, I created a gauge-java project that uses gradle as it's build tool. It runs the example template. 

I made it run on macOS, windows and linux against java versions : `[8, 9, 10, 11, 12, 13]`. The run passes with gauge `1.0.7` and gauge-java `0.7.4`.

The project is here: https://github.com/sriv/gauge-gradle-demo/

The run logs are here: https://github.com/sriv/gauge-gradle-demo/actions/runs/39235968

For those facing issues, can you please try to replicate it using this project as a template? Feel free to clone/fork this project.

**Comment by CosminSontu** [comment]
Retried today with Gauge 1.0.8.
Runs ok.

**Comment by gayanjanigamage** [comment]
Im trying in Gauge 1.0.8 and still getting this error

**Comment by sriv** [comment]
@gayanjanigamage 

The latest gauge release is 1.1.4. You may try using that.

Also, I hope you've read the [previous](https://github.com/getgauge/gauge/issues/1380#issuecomment-585721962) [comments](https://github.com/getgauge/gauge/issues/1380#issuecomment-586190443) that could give you some hints?

Please upgrade gauge and gauge-java to latest versions (make sure maven/gradle also point to the latest gauge-java) and if you still have problems, raise a new issue giving details on how we can replicate it.
