### ISSUE TITLE
When a test is failed gauge will take the whole desktop screen rather than driver screenshot

### ISSUE THREAD

**Issue by osandadeshan** [getgauge/gauge#1623]
### When a test is failed gauge will take the whole desktop screen rather than driver screenshot
I am having **[CustomScreenshotGrabber.kt](https://github.com/osandadeshan/kotlin-appium-gauge-demo/blob/master/src/test/kotlin/com/gauge/kotlin/util/CustomScreenshotGrabber.kt)** in my kotlin project
https://github.com/osandadeshan/kotlin-appium-gauge-demo

![image](https://user-images.githubusercontent.com/9147189/79767734-5fb78200-8347-11ea-8862-ec88c71982a8.png)

### What command(s) did you run when you found the bug?
```
gauge run specs
```

#### Gauge (Output of `gauge -v`)
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
flash (0.0.2)
html-report (4.0.9)
java (0.7.3)
js (2.3.8)
json-report (0.3.2)
reportportal (1.1.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

#### Node.js/Java/Python/.Net/Ruby version
Java 8

#### Operating System information
Windows 10 64 bit

#### IDE information
IntelliJ IDEA Community

**Comment by zabil** [comment]
The custom screenshot mechanism has completely changed in the latest versions of Gauge, gauge-java plugin and html-report. 

So to function you will need to upgrade gauge-java to 0.7.6 and add the following code for custom screenshots.

https://docs.gauge.org/writing-specifications.html?os=linux&language=java&ide=vscode#taking-custom-screenshots

**Comment by osandadeshan** [comment]
@zabil What about the issue was in Kotlin step implementation not found issue? Is it fixed in gauge-java to 0.7.6?

**Comment by zabil** [comment]
Unfortunately that is not fixed yet. You can follow the issue at
https://github.com/getgauge/gauge-java/issues/390

**Comment by osandadeshan** [comment]
I have to wait a bit until that is resolved then. Thanks @zabil
