### ISSUE TITLE
Mismatch of steps and table names in report when launch data driven spec in multithreading

### ISSUE THREAD

**Issue by donRumata83** [getgauge/gauge#1633]
Mismatch within steps and names in the table in the report after running data-driven specifications in multiple threads. The issue appears after upgrade from 1.0.6 to 1.0.8.

**Expected behavior**
Table data in report and steps bellow should be matched to each other

**Steps to reproduce:** 
- create data-driven spec with using data from table in step name
- run it multiple threads
- get report
- compare names in the table above and steps bellow 

**Versions**
_Configuration when the issue reproduced:_ 
Gauge version: 1.0.8
Commit Hash: 28617ea
html-report (4.0.10) or lower (also checked with 4.0.6 and 4.0.3)
java (0.7.4) or 0.7.3
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)

_Configuration when the issue didn't reproduce:_
Gauge version: 1.0.6
Commit Hash: 2bc49db
html-report (4.0.6)
java (0.7.3)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)

**Comands** 
gauge:execute 
-Dtags=%gauge.tags%
-DinParallel=true
-Dnodes=%parallel.threads%
-DspecsDir=%specsDir%

**Environment**
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-76-generic x86_64)

**Comment by Vitalinka-Brutalinka** [comment]
The same issue.

**Comment by fru2zzy** [comment]
Fix it please ASAP

**Comment by zabil** [comment]
@fru2zzy please use the versions mentioned where it is working for the time being.

i.e 
> Configuration when the issue didn't reproduce:
Gauge version: 1.0.6
Commit Hash: 2bc49db
html-report (4.0.6)
java (0.7.3)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.2)

**Comment by zabil** [comment]
@donRumata83 do you have some kind of a screen shot?

**Comment by fru2zzy** [comment]
> @fru2zzy please use the versions mentioned where it is working for the time being.
> 
> i.e
> 
> > Configuration when the issue didn't reproduce:
> > Gauge version: 1.0.6
> > Commit Hash: [2bc49db](https://github.com/getgauge/gauge/commit/2bc49db9240428741a3157f812d0c86efa688b24)
> > html-report (4.0.6)
> > java (0.7.3)
> > screenshot (0.0.1)
> > spectacle (0.1.3)
> > xml-report (0.2.2)

We have updated Gauge and plugins on all of our TeamCity agents because of bugs that persists in older versions and also it is not so easy to rollback :(

**Comment by donRumata83** [comment]
@zabil I can't give work screenshots, but if it necessary  I'll try to reproduce it from scratch and give some pictures.

**Comment by sriv** [comment]
@donRumata83, that won't be necessary. I could replicate the issue. We are working on this.

**Comment by donRumata83** [comment]
@sriv great to hear that! Thank you

**Comment by donRumata83** [comment]
Could you please give me any estimations for this issue?

**Comment by sriv** [comment]
@donRumata83 - @negiDharmendra is looking into this (among other things), and we hope to have some update by this week.

**Comment by negiDharmendra** [comment]
Hi @donRumata83, @fru2zzy, and @Vitalinka-Brutalinka we have pushed a fix for this issue.
It will be great if you can verify the fix by installing gauge for [here](https://github.com/getgauge/gauge/actions/runs/97074950).

**Comment by donRumata83** [comment]
Hi, @negiDharmendra, great news. I'll check it asap and give you feedback.

**Comment by donRumata83** [comment]
Unfortunately, the build didn't fix the problem. The first button in the table shown with correct steps below, but the other buttons have the same mismatch.
FYI since my starting report was written, we've updated our agents to 
Gauge version: 1.0.8
Commit Hash: 28617ea (when I've tested the new build: Commit Hash: 26b409d)
Plugins
-------
html-report (4.0.10)
java (0.7.7)
reportportal (1.3.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

**Comment by donRumata83** [comment]
Sorry for the delay, I've checked it looks like this build has fixed the issue.

**Comment by donRumata83** [comment]
@negiDharmendra @sriv Could you give any estimations about date of the next release?
