### ISSUE TITLE
Unable to run gauge sample project on linux environment

### ISSUE THREAD

**Issue by RatanHSC** [getgauge/gauge#242]
Hi,

I have set up the gauge and related plugin on my linux environment. I have verified it also as below:

[svc-prdsvc@nvprdappjk001uk gauge]$ gauge -v
Gauge version: 0.1.8

Plugins
-------
html-report (1.0.4)
java (0.2.2)
xml-report (0.0.2)

Now I have created the sample project like below:

[svc-prdsvc@nvprdappjk001uk gauge]$ gauge --init java
[INFO]  create  manifest.json

[INFO]  create  specs

[INFO]  create  specs/hello_world.spec

[INFO]  create  env

[INFO]  create  env/default

[INFO]  create  env/default/default.properties

create  src/test/java
create  libs
create  src/test/java/StepImplementation.java
create  env/default/java.properties
[INFO]
Successfully initialized the project. Run specifications with "gauge specs/"

While I am running the sample project getting error as below:

[svc-prdsvc@nvprdappjk001uk gauge]$ gauge specs/
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x68e2ef]

goroutine 14 [running]:
gopkg.in/fsnotify%2ev1.(*Watcher).isClosed(0x0, 0xc20805cbd0)
        /tmp/src/gopkg.in/fsnotify.v1/inotify.go:64 +0x1f
gopkg.in/fsnotify%2ev1.(*Watcher).Close(0x0, 0x0, 0x0)
        /tmp/src/gopkg.in/fsnotify.v1/inotify.go:73 +0x3a
gopkg.in/fsnotify%2ev1.(*Watcher).isClosed(0x0, 0x11)
        /tmp/src/gopkg.in/fsnotify.v1/inotify.go:64 +0x1f
gopkg.in/fsnotify%2ev1.(*Watcher).Add(0x0, 0xc20809c380, 0x11, 0x0, 0x0)
        /tmp/src/gopkg.in/fsnotify.v1/inotify.go:92 +0x83
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).addDirToFileWatcher(0xc20803f840, 0x0, 0xc20809c380, 0x11)
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:316 +0x4d
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges(0xc20803f840)
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:309 +0x627
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).MakeListOfAvailableSteps
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:46 +0x32

goroutine 1 [select]:
github.com/getgauge/gauge/execution.startApi(0xc208099320)
        /tmp/src/github.com/getgauge/gauge/execution/execute.go:48 +0x372
github.com/getgauge/gauge/execution.ExecuteSpecs(0xc20800a000, 0xc20800a010, 0x1, 0x1)
        /tmp/src/github.com/getgauge/gauge/execution/execute.go:35 +0x22e
main.main()
        /Applications/Go Agent.app/pipelines/Packaging/gauge.go:120 +0x5de

goroutine 6 [chan receive]:
github.com/getgauge/gauge/parser.ParseSpecFiles(0xc208032a10, 0x1, 0x1, 0xc20809c1c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/src/github.com/getgauge/gauge/parser/parse.go:38 +0x279
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).getParsedSpecs(0xc20803f840, 0xc208032a10, 0x1, 0x1, 0x0, 0x0, 0x0)
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:130 +0x136
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).initSpecsCache(0xc20803f840)
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:61 +0x199
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).MakeListOfAvailableSteps(0xc20803f840, 0xc20809dc00)
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:52 +0x83
github.com/getgauge/gauge/api.StartAPIService(0x0, 0xc20809ce40)
        /tmp/src/github.com/getgauge/gauge/api/api.go:72 +0x521
created by github.com/getgauge/gauge/execution.startApi
        /tmp/src/github.com/getgauge/gauge/execution/execute.go:47 +0x13c

goroutine 7 [select]:
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout(0xc20809cea0, 0x0, 0x0, 0x0, 0x0)
        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:91 +0x329
github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).HandleMultipleConnections(0xc20809cea0)
        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:139 +0x28
created by github.com/getgauge/gauge/api.StartAPIService
        /tmp/src/github.com/getgauge/gauge/api/api.go:66 +0x487

goroutine 8 [syscall]:
syscall.Syscall(0x0, 0x6, 0xc2080ae000, 0x8000, 0x1, 0x8000, 0x40e30f)
        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x6, 0xc2080ae000, 0x8000, 0x8000, 0xbaf6a0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x6, 0xc2080ae000, 0x8000, 0x8000, 0x7b5a60, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc2080462e8, 0xc2080ae000, 0x8000, 0x8000, 0xc2080ae000, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc2080462e8, 0xc2080ae000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
io.Copy(0x2b5397234b78, 0xba5458, 0x2b5397232c20, 0xc2080462e8, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x1f6
os/exec.func·003(0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc20809d8a0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:329 +0xb6d

goroutine 9 [chan receive]:
github.com/getgauge/gauge/runner.func·002()
        /tmp/src/github.com/getgauge/gauge/runner/runner.go:183 +0x59
created by github.com/getgauge/gauge/runner.startRunner
        /tmp/src/github.com/getgauge/gauge/runner/runner.go:186 +0x5cd

goroutine 10 [syscall]:
syscall.Syscall6(0x3d, 0x354a, 0xc20801b53c, 0x0, 0xc20805c870, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x354a, 0xc20801b53c, 0x0, 0xc20805c870, 0x90, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x354a, 0xc20801b584, 0x0, 0xc20805c870, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc20809dba0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc20809dba0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc208084500, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/os/exec/exec.go:364 +0x23c
github.com/getgauge/gauge/runner.func·003()
        /tmp/src/github.com/getgauge/gauge/runner/runner.go:211 +0x44
created by github.com/getgauge/gauge/runner.waitAndGetErrorMessage
        /tmp/src/github.com/getgauge/gauge/runner/runner.go:216 +0x11c

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc20809fa30, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20809fa30, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20809f9d0, 0x0, 0x2b5397232c70, 0xc208032818)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080461f0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080461f0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:244 +0x4c
github.com/getgauge/gauge/conn.func·002()
        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:82 +0x3f
created by github.com/getgauge/gauge/conn.(*GaugeConnectionHandler).acceptConnectionWithoutTimeout
        /tmp/src/github.com/getgauge/gauge/conn/connectionHandler.go:89 +0x1b1

goroutine 15 [runnable]:
github.com/getgauge/gauge/parser.parseSpec(0xc208098420, 0x22, 0xc20809c1c0, 0xc2080361e0, 0xc208036180)
        /tmp/src/github.com/getgauge/gauge/parser/parse.go:47
created by github.com/getgauge/gauge/parser.ParseSpecFiles
        /tmp/src/github.com/getgauge/gauge/parser/parse.go:35 +0x209

goroutine 16 [runnable]:
github.com/getgauge/gauge/api/infoGatherer.func·001()
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:291
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges
        /tmp/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:300 +0x270

Please help me to fix this issue.

**Comment by mahendrakariya** [comment]
It seems this error is because gauge is not able to access the `specs` directory. Could you please ensure that you have the necessary permissions for all the files in this project?

We have also released [Gauge v0.2.1](http://getgauge.io/download.html). Could you please upgrade to the latest version and try again? Once you install the latest version, please update all the plugins by running `gauge --update-all` before you run the specs.

**Comment by RatanHSC** [comment]
Hi Mahendra,

I had tried after upgrading gauge v0.2.1 but still facing the same issue.

**Comment by mahendrakariya** [comment]
Can you provide us the log messages? You can find them in `logs` directory of your project.

**Comment by RatanHSC** [comment]
Hi Mahendra,

Please find attached log file as I am unable to upload file from the github.

Thanks,
Ratan

**Comment by deepthigc** [comment]
Hey Ratan,

We still don't see any attached file. You can send it directly to
getgauge@googlegroups.com, github may be discarding you file.

Deepthi

**Comment by mahendrakariya** [comment]
We haven't heard from you in a while. Has this issue been resolved?

**Comment by jangam** [comment]
Hi Mahendra,

The issue has been resolved. This was the issue with the platform (OS) version. Thanks for your quick help.

**Comment by sriv** [comment]
@jangam - Thanks for letting us know, glad to see this solved.
