### ISSUE TITLE
current runner is not compatible with gauge LSP

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#991]
**Expected behavior**
If the current runner is compatible with LSP, LSP features should work seamlessly

**Actual behavior**
Getting the error `current runner is not compatible with gauge LSP`

**Observed on**
* The travis build for LSP is failing for the above reason https://travis-ci.org/getgauge/gauge-lsp-tests/builds/360125616

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-29
Commit Hash: b79de74
Plugins
-------
js (2.2.0.nightly-2018-03-29)
xml-report (0.2.1.nightly-2018-03-28)
```

**Comment by sguptatw** [comment]
The getRunnerLanguage is returning an empty string in this scenario.
```
10:42:33.075 notif #0: initialized: current runner is not compatible with gauge LSP
10:42:33.075 <-- notif: window/logMessage: {"type":1,"message":"notif #0: initialized: current runner is not compatible with gauge LSP"}
10:42:33.077 --> request #1: gauge/getRunnerLanguage: null
10:42:33.077 <-- result #1: gauge/getRunnerLanguage: ""
```

**Comment by nehashri** [comment]
This seems to be an issue with gauge-lsp-tests. This happens when the manifest file is not copied correctly in the tests. This is fixed in gauge-lsp-tests via [fd45ef8](https://github.com/getgauge/gauge-lsp-tests/commit/fd45ef8641a26f5b3a190a60dbe2b4a10e2462d5)

**Comment by Noob7** [comment]
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.8)
js (2.3.11)
screenshot (0.0.1)
xml-report (0.2.2)
 
still getting :(
